tasks:
  - init: |
      npm install
      npm run build
    command: |
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for pull requests
    pullRequests: true
    # enable for push to main
    branches: true
